// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlinePharmacy.Server.Data;

#nullable disable

namespace OnlinePharmacy.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240105042235_Alluptoseeding")]
    partial class Alluptoseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlinePharmacy.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "badf7177-8f2c-49ec-812b-d584f577d35c",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELKx4OeIUjXSCiyliczmtcsgC/54IE/i7tBDa/lSEhXx6z2XrcdTFUJFz1wi38HXsQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "58d78ff6-14f1-4dd1-89d2-df9c5d313ea4",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryDescription = "Medicines that needs prescription",
                            CategoryName = "Prescription Item"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryDescription = "Vitamins for your kids",
                            CategoryName = "Vitamins"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryDescription = "Medicines that allow to be purchasing over the counter",
                            CategoryName = "Over-The-Counter-Medicines"
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("CustAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustBlockNo")
                        .HasColumnType("int");

                    b.Property<string>("CustEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustFloorNo")
                        .HasColumnType("int");

                    b.Property<string>("CustFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustLname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustPhoneNo")
                        .HasColumnType("int");

                    b.Property<int?>("CustPostalCode")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            CustAddress = "Ubi Avenue 1",
                            CustBlockNo = 55,
                            CustEmail = "chaewon55@gmail.com",
                            CustFloorNo = 5,
                            CustFname = "Chae",
                            CustGender = "Female",
                            CustLname = "Won",
                            CustPass = "helloworld1",
                            CustPhoneNo = 83719378,
                            CustPostalCode = 123983
                        },
                        new
                        {
                            CustomerID = 2,
                            CustAddress = "Tampines Street 61",
                            CustBlockNo = 62,
                            CustEmail = "johnwick66@gmail.com",
                            CustFloorNo = 6,
                            CustFname = "John",
                            CustGender = "Male",
                            CustLname = "Wick",
                            CustPass = "helloworld2",
                            CustPhoneNo = 93682946,
                            CustPostalCode = 103933
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryID"));

                    b.Property<decimal?>("DeliveryCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstimatedDeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryID");

                    b.HasIndex("OrderID");

                    b.ToTable("Delivery");

                    b.HasData(
                        new
                        {
                            DeliveryID = 1,
                            DeliveryCost = 5m,
                            DeliveryMethod = "Standard",
                            DeliveryStatus = "Packing",
                            EstimatedDeliveryDate = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(7982),
                            EstimatedDeliveryTime = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8006),
                            OrderID = 1
                        },
                        new
                        {
                            DeliveryID = 2,
                            DeliveryCost = 5m,
                            DeliveryMethod = "Standard",
                            DeliveryStatus = "Packing",
                            EstimatedDeliveryDate = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8008),
                            EstimatedDeliveryTime = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8009),
                            OrderID = 2
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.OnlineConsultation", b =>
                {
                    b.Property<int>("OnlineConsultationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OnlineConsultationID"));

                    b.Property<DateTime?>("ConsultationDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConsultationDateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsultationDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsultationDuration")
                        .HasColumnType("int");

                    b.Property<string>("ConsultationPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ConsultationPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConsultationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultationSymptom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsultationTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConsultationTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("PharmacistID")
                        .HasColumnType("int");

                    b.Property<int?>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("OnlineConsultationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("OnlineConsultation");

                    b.HasData(
                        new
                        {
                            OnlineConsultationID = 1,
                            ConsultationDateEnd = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8177),
                            ConsultationDateStart = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8174),
                            ConsultationDuration = 1,
                            ConsultationPrice = 40m,
                            ConsultationTimeEnd = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8173),
                            ConsultationTimeStart = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8173),
                            CustomerID = 1,
                            PharmacistID = 1
                        },
                        new
                        {
                            OnlineConsultationID = 2,
                            ConsultationDateEnd = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8193),
                            ConsultationDateStart = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8192),
                            ConsultationDuration = 2,
                            ConsultationTimeEnd = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8192),
                            ConsultationTimeStart = new DateTime(2024, 1, 5, 4, 22, 34, 756, DateTimeKind.Utc).AddTicks(8191),
                            CustomerID = 2,
                            PharmacistID = 1
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("StaffID");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            CustomerID = 1,
                            OrderDate = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8933),
                            OrderTime = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8934),
                            StaffID = 2
                        },
                        new
                        {
                            OrderID = 2,
                            CustomerID = 2,
                            OrderDate = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8942),
                            OrderTime = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(8942),
                            StaffID = 2
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemQty")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrderItemSubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OnlineConsultationID")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionID");

                    b.HasIndex("OnlineConsultationID");

                    b.ToTable("Prescription");

                    b.HasData(
                        new
                        {
                            PrescriptionID = 1,
                            ExpiryDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            IssueDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            OnlineConsultationID = 1
                        },
                        new
                        {
                            PrescriptionID = 2,
                            ExpiryDate = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            IssueDate = new DateTime(2024, 1, 5, 12, 22, 34, 756, DateTimeKind.Local).AddTicks(9819),
                            OnlineConsultationID = 2
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.PrescriptionItem", b =>
                {
                    b.Property<int>("PrescriptionItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionItemID"));

                    b.Property<int>("PrescriptionID")
                        .HasColumnType("int");

                    b.Property<int?>("PrescriptionItemQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrescriptionItemSubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionItemID");

                    b.HasIndex("PrescriptionID");

                    b.HasIndex("ProductID");

                    b.ToTable("PrescriptionItem");

                    b.HasData(
                        new
                        {
                            PrescriptionItemID = 1,
                            PrescriptionID = 1,
                            PrescriptionItemQuantity = 1,
                            PrescriptionItemSubTotal = 10m,
                            ProductID = 3
                        },
                        new
                        {
                            PrescriptionItemID = 2,
                            PrescriptionID = 2,
                            PrescriptionItemQuantity = 2,
                            PrescriptionItemSubTotal = 20m,
                            ProductID = 4
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool?>("PrescriptionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ProductBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProductExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductIngredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductUsage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            PrescriptionStatus = false,
                            ProductBrand = "SCOTT'S",
                            ProductCategoryID = 2,
                            ProductDescription = "Scott's is the Number 1 Kids' Multivitamin Brand in Singapore*. Worry about your little ones being picky with food and not getting the necessary nutrients for proper growth/development? Do not worry, Scott’s Multivitamin Gummies is coming to your rescue! Available in three delicious fruity flavors Apple, Tropical Fruits, and the NEWEST addition - Mango; it contains Zinc and five essential vitamins - A, B6, C, D, E - to support your kid immunity, bone growth and healthy vision every day. Moreover, Scott's micro encapsulation technology locks in the goodness of Zinc and 5 Vitamins (Vitamin A, B6, C, D & E) whilst giving kids the taste they love.",
                            ProductDosage = "3x/Day",
                            ProductExpiryDate = new DateTime(2024, 1, 5, 4, 22, 34, 757, DateTimeKind.Utc).AddTicks(791),
                            ProductIngredients = "Glucose, Syrup, Sugar, Gelatin, Acidity Regulator (Citric Acid, Sodium Citrate), Humectant (Sorbitol), Flavouring substance, Vitamins and Mineral (Vitamin C, Zinc, Vitamin E, Vitamin B6, Vitamin A and Vitamin D) and Colouring substance (Tartrazine)\r\n",
                            ProductName = "SCOTT'S Multivitamins Gummies Mango",
                            ProductPrice = 22m,
                            ProductUsage = "Strong bones and teeth, improve the immune system, growth and development",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 2,
                            PrescriptionStatus = false,
                            ProductBrand = "Panadol",
                            ProductCategoryID = 3,
                            ProductDescription = "Panadol Children’s Suspension 1-6 Years (120mg/5ml) provides relief from fever and pain in children aged 1 to 6 years. Like all Children’s Panadol products, Panadol Children’s Suspension 1-6 Years is gentle on little stomachs. A strawberry-flavoured suspension, Panadol Children’s Suspension 1-6 Years contains no alcohol and is aspirin-free.",
                            ProductDosage = "5-10ml (based on child's weight 9.5-19.5kg)\nDo not take more frequently than once every 4 Hours and do not exceed more than four doses in 24 hours. Do not take for more than 3 days without asking your doctor.",
                            ProductExpiryDate = new DateTime(2024, 1, 5, 4, 22, 34, 757, DateTimeKind.Utc).AddTicks(795),
                            ProductIngredients = "Active ingredient: 120 mg/5 ml Paracetamol\r\nExcipients: No Alcohol, no Aspirin.",
                            ProductName = "Panadol Children's Suspension",
                            ProductPrice = 9m,
                            ProductUsage = "Fever, Headaches, Symptoms of colds and flu, Teething pain, Toothaches, Earache, Pain associated with immunisation",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductID = 3,
                            PrescriptionStatus = true,
                            ProductBrand = "Amoxil",
                            ProductCategoryID = 1,
                            ProductDescription = "Amoxicillin is a penicillin antibiotic. It is used to treat bacterial infections, such as chest infections (including pneumonia) and dental abscesses. It can also be used together with other antibiotics and medicines to treat stomach ulcers.",
                            ProductDosage = "1.25-12.5ml (based on child's weight 3.6-36kg)\nGive this dose three (3) times a day—once in the morning, once at mid-day, and once in the evening—for as long as directed.",
                            ProductExpiryDate = new DateTime(2024, 1, 5, 4, 22, 34, 757, DateTimeKind.Utc).AddTicks(798),
                            ProductIngredients = "Croscarmellose sodium, gelatin, magnesium stearate, titanium dioxide, and yellow iron oxide.",
                            ProductName = "Amoxicillin",
                            ProductPrice = 10m,
                            ProductUsage = "Bacterial infections, such as chest infections (including pneumonia) and dental abscesses. Can also be used together with other antibiotics and medicines to treat stomach ulcers.",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 4,
                            PrescriptionStatus = true,
                            ProductBrand = "Ibuprofen",
                            ProductCategoryID = 1,
                            ProductDescription = "Ibuprofen is a nonsteroidal anti-inflammatory drug.",
                            ProductDosage = "Ibuprofen dose is 400mg(two tablets) to be taken initially. 200mg(one tablet) to 400mg(two tablets) may be taken every 4 hours when required.",
                            ProductExpiryDate = new DateTime(2024, 1, 5, 4, 22, 34, 757, DateTimeKind.Utc).AddTicks(843),
                            ProductIngredients = "Lactose, Maize Starch, Hypromellose, Sodium Starch Glycollate, Colloidal Anhydrous Silica, Magnesium Stearate, Sucrose, Talc, Titanium Dioxide (E171) and Carnauba Wax",
                            ProductName = "Ibuprofen",
                            ProductPrice = 10m,
                            ProductUsage = "Treat fever, pain, and inflammation in children",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 5,
                            PrescriptionStatus = false,
                            ProductBrand = "Zyrtec",
                            ProductCategoryID = 3,
                            ProductDescription = "Zyrtec pcs 10's is now Zyrtec-R pcs 10's.\r\nNew Name, New Pack, Same Formula.\r\nZyrtec-R is an antihistamine.",
                            ProductDosage = "Children aged from 2 to 6 years: 2.5 mL of oral solution (half of a spoon) twice daily. Children aged from 6 to 12 years: 5 mg [10 drops, or 5 ml oral solution (1 full spoon) or half of the tablet] twice daily.",
                            ProductExpiryDate = new DateTime(2024, 1, 5, 4, 22, 34, 757, DateTimeKind.Utc).AddTicks(845),
                            ProductIngredients = "",
                            ProductName = "Zyrtec R",
                            ProductPrice = 12m,
                            ProductUsage = "Treats allergy symptoms like itchy eyes, sneezing, a stuffy nose or hives",
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffLname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staff_pass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            Position = "Pharmacist",
                            StaffFname = "Tom",
                            StaffGender = "Male",
                            StaffLname = "Lim",
                            Staff_email = "tomlim@blazor.com",
                            Staff_pass = "P@ssword2"
                        },
                        new
                        {
                            StaffID = 2,
                            Position = "Order Clerk",
                            StaffFname = "Mary",
                            StaffGender = "Female",
                            StaffLname = "Ong",
                            Staff_email = "maryong@blazor.com",
                            Staff_pass = "P@ssword3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlinePharmacy.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlinePharmacy.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlinePharmacy.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlinePharmacy.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Delivery", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.OnlineConsultation", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlinePharmacy.Shared.Domain.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID");

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Order", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlinePharmacy.Shared.Domain.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.OrderItem", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlinePharmacy.Shared.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Prescription", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.OnlineConsultation", "OnlineConsultation")
                        .WithMany()
                        .HasForeignKey("OnlineConsultationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnlineConsultation");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.PrescriptionItem", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlinePharmacy.Shared.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlinePharmacy.Shared.Domain.Product", b =>
                {
                    b.HasOne("OnlinePharmacy.Shared.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
